server:
  port: 8080

# Oauth client 설정은 ClientRegistrationRepository Bean으로도 설정이 가능하다.
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: oauth2-client-app
            client-secret: WYSyfEdtjIx1DTqlggyWVmtmJ1EVHnI0
            client-name: test
            redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic # base64로 인코딩하는 방식. {etc: client_secret_post, none(퍼블릭 클라이언트)}
#            client-authentication-method: client_secret_post # Form 제출 방식
#            client-authentication-method: none # 퍼블릭 클라이언트)
            scope:
              - openid
              - profile
              - email 
        provider:
          keycloak:
            authorization-uri: http://localhost:9090/realms/oauth2/protocol/openid-connect/auth
            token-uri: http://localhost:9090/realms/oauth2/protocol/openid-connect/token
            issuer-uri: http://localhost:9090/realms/oauth2
            user-info-uri: http://localhost:9090/realms/oauth2/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:9090/realms/oauth2/protocol/openid-connect/certs
            user-name-attribute: preferred_username